# Generated by Django 5.0.3 on 2026-05-03 18:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Engagement',
            fields=[
                ('engagement_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('groom_name', models.CharField(max_length=255)),
                ('bride_name', models.CharField(max_length=255)),
                ('engagement_date', models.DateField()),
                ('engagement_location', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'engagement',
            },
        ),
        migrations.CreateModel(
            name='Marriage',
            fields=[
                ('marriage_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('groom_name', models.CharField(max_length=255)),
                ('bride_name', models.CharField(max_length=255)),
                ('marriage_date', models.DateField()),
                ('marriage_location', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'marriage',
            },
        ),
        migrations.CreateModel(
            name='Reception',
            fields=[
                ('reception_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('groom_name', models.CharField(max_length=255)),
                ('bride_name', models.CharField(max_length=255)),
                ('reception_date', models.DateField()),
                ('reception_location', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'reception',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=255)),
                ('user_mobile', models.CharField(max_length=255)),
                ('user_email', models.CharField(max_length=255, unique=True)),
                ('user_type', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=255)),
                ('has_marriage', models.BooleanField(default=False)),
                ('has_reception', models.BooleanField(default=False)),
                ('has_engagement', models.BooleanField(default=False)),
                ('event_engagement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event', to='users.engagement')),
                ('event_marriage', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event', to='users.marriage')),
                ('event_reception', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event', to='users.reception')),
            ],
            options={
                'db_table': 'event',
            },
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('invitation_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name1', models.CharField(max_length=255)),
                ('name2', models.CharField(blank=True, max_length=255)),
                ('name3', models.CharField(blank=True, max_length=255)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='users.event')),
            ],
            options={
                'db_table': 'invitation',
            },
        ),
        migrations.CreateModel(
            name='UserEvent',
            fields=[
                ('user_event_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='users.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='users.user')),
            ],
            options={
                'db_table': 'user_events',
                'unique_together': {('user', 'event')},
            },
        ),
    ]
